# Generated by Django 3.0.2 on 2020-01-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20200118_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
