# Generated by Django 3.0.2 on 2020-01-18 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do', '0003_auto_20200118_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('user', 'title')},
        ),
    ]
